server:
  port: 8080
  address: 0.0.0.0

spring:
  profiles:
    active: ${ENV:local}
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB

jwt:
  secret: REDACTED
  expiration: 86400000

logging:
  level:
    com.example.litelog: INFO
    org.springframework.security: INFO

avatar:
  upload:
    path: ./uploads/avatars
  base:
    url: http://10.226.12.52:8080/api/avatars

record:
  image:
    upload:
      path: ./uploads/records
    base:
      url: http://10.226.12.52:8080/api/record-images
