server:
  port: 8080
  address: 0.0.0.0

spring:
  profiles:
    active: ${ENV:local}
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB

logging:
  level:
    com.example.litelog: INFO
    org.springframework.security: INFO

oss:
  endpoint: oss-cn-shanghai.aliyuncs.com
  bucket: litelog-assets
  access-key-id: ${ALIBABA_ACCESS_KEY}
  access-key-secret: ${ALIBABA_SECRET_KEY}
  url-prefix: https://litelog-assets.oss-cn-shanghai.aliyuncs.com

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
